# Generated by Django 4.1.7 on 2023-02-22 10:06

from django.db import migrations
from faker import Faker

fake = Faker()


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20230222_0915'),
    ]

    # Create migration data for table store_category
    length = 10
    cat_range = range(length)
    category_data = ""
    for i in cat_range:
        title = fake.name()
        category_data += "('" + title + "')"
        if i != length - 1:
            category_data += ',\n'
    category_data = f"""{category_data}"""

    operations = [
                migrations.RunSQL(f"""
                        INSERT INTO store_category (title)
                        VALUES {category_data} ON CONFLICT DO NOTHING;
                    """, """
                        DELETE FROM store_category
                    """)
            ]

