# Generated by Django 4.1.7 on 2023-02-23 07:20
import random
from datetime import datetime

from django.db import migrations
from faker import Faker
from store import models
from store.models import Customer

fake = Faker()
PAYMENT_STATUS = [
    models.PAYMENT_STATUS_PENDING,
    models.PAYMENT_STATUS_COMPLETE,
    models.PAYMENT_STATUS_FAILED
]


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20230223_0944'),
    ]

    # Create migration data for table store_order
    length = 10
    order_range = range(length)
    order_data = ""
    for i in order_range:
        placed_at = datetime.now()
        payment_status = random.choice(PAYMENT_STATUS)
        customer_id = Customer.objects.order_by('?').values_list('id', flat=True)[0]

        order_data += "('" + str(placed_at) + "','" + payment_status + "','" + str(customer_id) + "')"
        if i != length - 1:
            order_data += ',\n'
    order_data = f"""{order_data}"""

    operations = [
        migrations.RunSQL(f"""
                            INSERT INTO store_order (placed_at, payment_status, customer_id)
                            VALUES {order_data} ON CONFLICT DO NOTHING;
                        """, """
                            DELETE FROM store_order
                        """)
    ]
