# Generated by Django 4.1.7 on 2023-02-23 07:30
import random

from django.db import migrations
from faker import Faker

from store.models import Product

fake = Faker()


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20230223_1420'),
    ]

    # Create migration data for table store_orderitem
    length = 10
    orderitem_range = range(length)
    orderitem_data = ""
    for i in orderitem_range:
        order_id = i + 1
        product_id = Product.objects.order_by('?').values_list('id', flat=True)[0]
        quantity = random.randint(0, 5)
        unit_price = Product.objects.filter(pk=product_id).values_list('unit_price', flat=True)[0]

        orderitem_data += "('" \
                          + str(order_id) + "','" \
                          + str(product_id) + "','" \
                          + str(quantity) + "','" \
                          + str(unit_price) \
                          + "')"
        if i != length - 1:
            orderitem_data += ',\n'
    orderitem_data = f"""{orderitem_data}"""

    operations = [
        migrations.RunSQL(f"""
                                INSERT INTO store_orderitem (order_id, product_id, quantity, unit_price)
                                VALUES {orderitem_data} ON CONFLICT DO NOTHING;
                            """, """
                                DELETE FROM store_orderitem
                            """)
    ]