# Generated by Django 4.1.7 on 2023-02-23 08:15

from django.db import migrations
from faker import Faker

fake = Faker()


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20230223_1430'),
    ]

    # Create migration data for table store_promotion
    length = 5
    promotion_range = range(length)
    promotion_data = ""
    for i in promotion_range:
        description = fake.name()
        discount = fake.pyfloat(positive=True, right_digits=2, left_digits=2)

        promotion_data += "('" \
                          + description + "','" \
                          + str(discount) \
                          + "')"
        if i != length - 1:
            promotion_data += ',\n'
    promotion_data = f"""{promotion_data}"""

    operations = [
        migrations.RunSQL(f"""
                                    INSERT INTO store_promotion (description, discount)
                                    VALUES {promotion_data} ON CONFLICT DO NOTHING;
                                """, """
                                    DELETE FROM store_promotion
                                """)
    ]
