# Generated by Django 4.1.7 on 2023-02-23 08:19

from django.db import migrations

from store.models import Product, Promotion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20230223_1515'),
    ]

    # Create migration data for table store_product_promotion
    length = 10
    product_promotion_range = range(length)
    product_promotion_data = ""
    for i in product_promotion_range:
        product_id = Product.objects.order_by('?').values_list('id', flat=True)[0]
        promotion_id = Promotion.objects.order_by('?').values_list('id', flat=True)[0]

        product_promotion_data += "('" \
                          + str(product_id) + "','" \
                          + str(promotion_id) \
                          + "')"
        if i != length - 1:
            product_promotion_data += ',\n'
    product_promotion_data = f"""{product_promotion_data}"""

    operations = [
        migrations.RunSQL(f"""
                                        INSERT INTO store_product_promotion (product_id, promotion_id)
                                        VALUES {product_promotion_data} ON CONFLICT DO NOTHING;
                                    """, """
                                        DELETE FROM store_product_promotion
                                    """)
    ]
