# Generated by Django 4.1.6 on 2023-03-15 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_custom', '0003_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='UserProfile',
        ),
    ]
