# Generated by Django 4.1.6 on 2023-02-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_remove_snippet_highlighted'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='decimal_field',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
        ),
    ]
