# Generated by Django 4.1.6 on 2023-02-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_alter_snippet_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnippetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
