# Generated by Django 4.1.6 on 2023-02-28 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_snippetcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to='snippets.snippetcategory'),
            preserve_default=False,
        ),
    ]
