# Generated by Django 4.1.6 on 2023-03-01 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0009_snippettag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippettag',
            name='created',
        ),
    ]
