# Generated by Django 4.1.6 on 2023-03-03 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0010_remove_snippettag_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippettag',
            name='snippet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='snippet_tags', to='snippets.snippet'),
            preserve_default=False,
        ),
    ]
